# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Veronica Hernandez
email: vlhernandez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Design, Portfolio and Fun Projects of Veronica Hernandez
url: "http://vlhernandez.com" # the base hostname & protocol for your site
twitter_username: vlhernandez_
github_username: vlhernandez
instagram_username: vlhernandez_
paginate: 3
# excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
permalink: /:title

#Default Settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project of type described below
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Veronica Hernandez
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project of type described below
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"

gems: [jekyll-paginate]
